### ISSUE TITLE
Using component waze_travel_time but it's not in 'dependencies' or 'after_dependencies'

### ISSUE THREAD

**Issue by rodpayne** [home-assistant/actions#28]
## What is happening:

I have been struggling to get my custom integration through the `hassfest` validation.  I have an import for `WazeRouteCalculator` and `hassfest` says: 
```
[DEPENDENCIES] Using component waze_travel_time but it's not in 'dependencies' or 'after_dependencies'
```

## What I don't understand:

I am using the `WazeRouteCalculator` project rather that the `waze_travel_time` integration.  The `waze_travel_time` is using `WazeRouteCalculator`, but not the other way around.  Why does it get pulled in to the check?

## What I have tried:

If I do what it says and add `waze_travel_time` to the dependencies in manifest.json, then the Home Assistant startup reports:
```
2021-03-08 08:57:10 ERROR (MainThread) [homeassistant.setup] Setup failed for waze_travel_time: No setup function defined.
2021-03-08 08:57:23 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of person_location. Setup failed for dependencies: waze_travel_time
```
I have tried `from WazeRouteCalculator import WazeRouteCalculator` instead of `import WazeRouteCalculator` to cut down the import.

I have tried adding adding `"WazeRouteCalculator>=0.12"` to requirements instead of `waze_travel_time` in dependencies.  This adds an additional error to the HACS validation, but at least Home Assistant starts normally:
```
❌ Python wheels (more-info: https://hacs.xyz/docs/publish/include#check-wheels )
```

This is in my development branch... https://github.com/rodpayne/home-assistant_person_location/tree/development.

Can you give me any ideas on where things are going wrong?  (My integration, the waze_travel_time integration, a mixup in the name space, or the validation?)

**Comment by rodpayne** [comment]
I tried one more thing...  I added `waze_travel_time` to `after_dependencies`.

Home Assistant starts normally and the push passes all of the validations.

I still don't understand what was happening.

**Comment by ludeeus** [comment]
This is not an issue for this repo, if you still have questions about how hassfest works, I suggest you join [Discord](https://discord.gg/c5DvZ4e) and ask in the #devs_core channel
