### ISSUE TITLE
Convert CLA bot to a GitHub action

### ISSUE THREAD

**Issue by balloob** [home-assistant/actions#3]
Not sure what would be involved, but it would be nice if we can migrate this too.

https://github.com/home-assistant/cla-bot

**Comment by robbiet480** [comment]
When you say migrate, you mean you want the entire CLA flow inside of actions, or just migrate from using the webhook + commit status to an action?

We'd still need a database of some kind to store signatures which I don't think Actions provides (yet) so not sure what the value would be of migrating if we still needed AWS for a large part of it.

**Comment by balloob** [comment]
Ah, that's a good point. Yeah, let's keep it as is. Better not touch a working thing anyway. I don't expect us to add any features ever.
