### ISSUE TITLE
Hassfest Failure: Don't specify title in translation strings if it's a brand name 

### ISSUE THREAD

**Issue by h4de5** [home-assistant/actions#70]
Hello, 

I am getting the following error message from hassfest validation, which I can't find any more information about:

```[TRANSLATIONS] Don't specify title in translation strings if it's a brand name or add exception to ALLOW_NAME_TRANSLATION```

I thought removing the "title" string from translations would solve the problem, but it didn't. 

https://github.com/h4de5/home-assistant-toshiba_ac/commit/5dc7ccc468bcfb8bbca632c2879a87bfb531442f

Any help or pointer in the right direction is appreciated.

**Comment by frenck** [comment]
Still there: <https://github.com/h4de5/home-assistant-toshiba_ac/blob/a4b7ba85b1e93c38a323daf3b7306e82471d544d/custom_components/toshiba_ac/strings.json#L2> 

😄 

It uses the strings.json file (as that contains the source strings).

../Frenck
