### ISSUE TITLE
Hassfest action failing on translations/json parsing (docker image)

### ISSUE THREAD

**Issue by CoMPaTech** [home-assistant/actions#80]
When running hassfest as  instructed (and we have it running for a while already) on a `custom_component` it errors on one of the json files for translation, e.g.

```
* [ERROR] [TRANSLATIONS] Invalid strings.json: extra keys not allowed (...)
```
[example on custom component ci](https://github.com/plugwise/plugwise-beta/actions/runs/3651734153/jobs/6169298044)

In our instance for an otherwise working `strings.json` and `translations/en.json` file. Reproducing with manually building the docker image locally concur. Changing the `Dockerfile` to use `home-assistant:dev` instead of `:beta` does not yield this error. Didn't dive into it further since we also run the `hassfest` from a core-clone, but there is definitely something not correct in the current image on docker [hub](https://hub.docker.com/layers/homeassistant/home-assistant/beta/images/sha256-900e8afff27226286ccf905c0d34ca3f049446053e3eebc12d954639f0a6dd77?context=explore)

**Comment by frenck** [comment]
The translation features used for Home Assistant 2023.1, this is not in beta or stable yet.
Hassfest runs against stable and the upcoming stables (beta) versions, not dev.

../Frenck
