### ISSUE TITLE
Manifest keys have been sorted

### ISSUE THREAD

**Issue by duhow** [home-assistant/actions#86]
```
Error: R] [MANIFEST] Manifest keys have been sorted: domain, name, then alphabetical order
```

Changes were valid at January 30th. Did something change?
Affects this [manifest.json](https://github.com/duhow/hass-aigues-barcelona/blob/10206be23cafd3c3cc874c307b9ebc93e415a94b/custom_components/aigues_barcelona/manifest.json) file.
https://github.com/duhow/hass-aigues-barcelona/

**Comment by ludeeus** [comment]
The message is slightly misleading:
`Manifest keys have to be sorted: domain, name, then alphabetical order`
Meaning that you need to sort the keys in your manifest.json file to the expected sorting order.

**Comment by duhow** [comment]
I understand the action requested. The question is, was this change in purpose? Is it announced somewhere?

**Comment by duhow** [comment]
@ludeeus @frenck ?

**Comment by th3w1zard1** [comment]
Same question, out of nowhere am now dealing with the issue over on a custom component fork at https://github.com/th3w1zard1/adaptive-lighting
