### ISSUE TITLE
Entity translation: hassfest failing when entity state key is capitalized

### ISSUE THREAD

**Issue by RobertD502** [home-assistant/actions#87]
The Hassfest workflow is failing when defining an entity state starting with a capital letter. For example, I have a select entity that allows selecting litter type including "Bentonite", "Tofu", and "Mixed".

Within strings.json and en.json the entity is defined in this manner:

```
        "litter_type": {
          "name": "Litter type",
          "state": {
            "Bentonite": "Bentonite",
            "Tofu": "Tofu",
            "Mixed": "Mixed"
          }
```

However, the hassfest workflow fails as a result of the select states being capitalized. Is it possible to soften the requirements for entity states or will the workflow only succeed if I rename the states (and in turn result in breaking changes for the end users of my component)?

Hassfest error output:

```
Error: R] [TRANSLATIONS] Invalid strings.json: Invalid translation key 'Bentonite', need to be [a-z0-9-_]+ and cannot start or end with a hyphen or underscore. for dictionary value @ data['entity']['select']['litter_type']['state']. Got {'Bentonite': 'Bentonite', 'Tofu': 'Tofu', 'Mixed': 'Mixed'}
```

**Comment by agners** [comment]
Given this https://github.com/home-assistant/core/pull/91288#issuecomment-1505705087 I am closing this issue.

**Comment by RobertD502** [comment]
No problem. I've already converted all keys in my integration to allow for the validation to pass.
