### ISSUE TITLE
hassfest: Unable to parse package version when requirement contains git

### ISSUE THREAD

**Issue by mill1000** [home-assistant/actions#92]
I'm attempting to run hassfest against a custom component that currently uses a git repository as a requirement. I'm using the format specified by the [docs here](https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing). 

e.g.
```json
"requirements": ["git+https://github.com/mill1000/midea-msmart.git"],
```

hassfest is failing with the following error:

> Error: R] [REQUIREMENTS] Unable to parse package version (+https://github.com/mill1000/midea-msmart.git) for git.

**Comment by rytilahti** [comment]
Related to https://github.com/home-assistant/developers.home-assistant/pull/2125

**Comment by andyb2000** [comment]
This appears to still be an issue, however based o the updated docs
```
{
  "requirements": ["<project> @ git+https://github.com/<user>/<project>.git@<git ref>"]
}
``` 

hassfest errors out with Error: R] [REQUIREMENTS] Requirement ...blah... contains a space

It seems to be failing due to the <project>_SPACE_@_SPACE_
Is this a fault in hassfest or hass?

**Comment by mpw96** [comment]
Components that declare a requirement as stated above to work as expected. It seems that just the hassfest test is not aware of this format.

**Comment by mpw96** [comment]
Hi I just wanted hassfest in my component not to cmplain anymore, that's why I proposed the change - I hope I didn't make things worse for anybody! [Here](https://github.com/mpw96/homeassistant-goecharger/blob/28f1e5c7aceb3de61115ed107e50269422256f91/custom_components/goecharger/manifest.json#L12-L14) is what works for me:
```
  "requirements": [
    "git+https://github.com/mpw96/goecharger.git@0.1.1"
  ],
```

So your code should be like this I think:
```
...
"requirements": ["git+https://github.com/alistair23/AutoMower-BLE.git@main"],
...
```

Does it work?

**Comment by mpw96** [comment]
So what @mill1000 needs should actually work now.

**Comment by mill1000** [comment]
I ran a test here and it seems to be working: https://github.com/mill1000/midea-ac-py/pull/268

**Comment by andyb2000** [comment]
> "requirements": ["git+https://github.com/alistair23/AutoMower-BLE.git@main"],

thanks, yes using this formatting now works, I'll put a PR in to update documentation as I think that will still be throwing people off.

Thanks all :)
