### ISSUE TITLE
Issue with manifest key sort validation?

### ISSUE THREAD

**Issue by raman325** [home-assistant/actions#95]
In #devs, someone reported that they were getting the following error when running the action:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 244, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 166, in main
    plugin.validate(integrations, config)
  File "/usr/src/homeassistant/script/hassfest/manifest.py", line 393, in validate
    subprocess.run(
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pre-commit', 'run', '--hook-stage', 'manual', 'prettier', '--files', PosixPath('/github/workspace/custom_components/netzooe_eservice/manifest.json')]' returned non-zero exit status 1.
Validating manifest...
```

It turns out their keys weren't sorted, but this error is obviously unhelpful and doesn't tell them that.

~~Wondering if there is an issue here with setting up pre-commit - from what I can tell, the Dockerfile installs requirements.txt but that doesn't contain pre-commit, and I think the pre-commit config would also have to be included so that prettier is installed as a pre-commit item.~~ EDIT: It looks like this is missing pre-commit. I THINK just by installing pre-commit, that this will work?

~~I may attempt to PR this but someone with more knowledge of this than me would probably be able to get it done faster 🙂~~

**Comment by leranp** [comment]
same here

**Comment by leranp** [comment]
After the fix how can i run the hassfest test with the new PR?
https://github.com/leranp/HomeAssistant-galatz-news/blob/main/.github/workflows/hassfest.yml

**Comment by raman325** [comment]
a new ghcr.io/home-assistant/home-assistant:beta container needs to be pushed. Unclear how often that happens

**Comment by ludeeus** [comment]
It happens on all stable and beta releases.
But it also needs to be included in the release that triggers the build (picked for 2023.9.x, or the next beta for 2023.10)

**Comment by raman325** [comment]
> It happens on all stable and beta releases. But it also needs to be included in the release that triggers the build (picked for 2023.9.x, or the next beta for 2023.10)

ack, will tag it then
